version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: sony
      MYSQL_DATABASE: demo_product
    ports:
      - "3306:3306"

  backend:
    build: ./demo
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: 
      context:  ./demo-product
      args:
        VITE_API_URL: http://52.90.98.175:8080/api
    container_name: react-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
